In [1]:
import scipy
from matplotlib import pyplot as plt
import scipy
from matplotlib import pyplot as plt
import numpy as np
from scipy.misc import imresize
import os
from scipy.misc import imread


In [2]:
def rgb2gray(rgb):
    return np.dot(rgb[...,:3], [0.299, 0.587, 0.114])

In [3]:
def safe(img):
    all_dim=img.shape
    if all_dim[0]>=25 and all_dim[1]>=25:
        return True
    else:
        return False

In [4]:
path1=r"C:\Users\akash\Downloads\Compressed\GTSRB_Final_Training_Images\GTSRB\Final_Training\Images"
imgs =[]
labels =[]
i=-1
for file1 in os.listdir(path1):
    path=os.path.join(path1, file1)
    i=i+1
    for file in os.listdir(path):
        if '.csv' in file :
            continue
        img = plt.imread(os.path.join(path,file))
        img=rgb2gray(img)
        if safe(img)==False:
            continue
        img = imresize(img,(25,25))
        imgs.append(img)
        labels.append(i)
imgs = np.array(imgs)
label = np.array(labels)


c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  from ipykernel import kernelapp as app


In [5]:
labels=np.array(labels)

In [6]:
print(labels.shape)

(39209,)


In [7]:
train_features=imgs
train_labels=labels

In [8]:
### rxtract labels for testing data----------------
def extract_labe_from_test_csv():
    test_labels=[]
    filename=r"C:\Users\akash\Downloads\Compressed\GTSRB_Final_Test_GT\GT-final_test.csv"
    i=0
    with open(filename, "rt") as f:
        for line in f:
            if(i==0):
                i=1
                continue
            x = line.split(';')[7]
            x=int(x)
            test_labels.append(x)
    return test_labels
        

In [9]:
test_labels=extract_labe_from_test_csv()

In [10]:
test_labels=np.array(test_labels)

In [11]:
print(test_labels.shape)

(12630,)


In [12]:
### read test images for testing features--------------
path1=r"C:\Users\akash\Downloads\Compressed\GTSRB_Final_Test_Images\GTSRB\Final_Test\Images"
imgs =[]
labels =[]
for file1 in os.listdir(path1):
    path=os.path.join(path1, file1)
    img = plt.imread(path)
    img=rgb2gray(img)
    if safe(img)==False:
            continue
    img = imresize(img,(25,25))
    imgs.append(img)
imgs = np.array(imgs)

c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  # This is added back by InteractiveShellApp.init_path()


In [13]:
test_features=imgs

In [14]:
print(test_features)

[[[236 235 236 ... 213 211 202]
  [239 238 237 ... 242 243 241]
  [240 237 235 ... 246 245 243]
  ...
  [232 230 228 ... 234 233 236]
  [231 228 228 ... 231 231 234]
  [227 227 230 ... 229 232 234]]

 [[ 40  53  59 ...  35  37  41]
  [ 41  56  56 ...  31  43  44]
  [ 39  53  55 ...  32  36  40]
  ...
  [ 22  41  44 ...  32  42  43]
  [ 22  39  43 ...  26  34  38]
  [ 21  39  43 ...  26  34  40]]

 [[ 28  27  26 ...  30  30  31]
  [ 34  34  34 ...  28  29  29]
  [ 42  42  42 ...  36  36  36]
  ...
  [  6   7  10 ...   3   4   5]
  [ 10  14  19 ...  10  13  19]
  [ 13  16  33 ...  19  24  28]]

 ...

 [[ 45  41  42 ...  49  49  50]
  [ 45  43  42 ...  49  50  52]
  [ 43  40  38 ...  46  47  46]
  ...
  [  8   5   7 ...  18  29  25]
  [  6   3   4 ...  20  28  27]
  [  4   3   2 ...  23  26  26]]

 [[169 166 121 ... 124  48   9]
  [217 209 169 ...  97  49  12]
  [231 241 230 ... 128  80  23]
  ...
  [ 44  37  37 ...  84 101  74]
  [ 24  20  18 ...  67  89  77]
  [ 17  15  13 ...  76  91  

In [15]:
test_features.shape

(12630, 25, 25)

In [16]:
print(train_features.shape)
print(train_labels.shape)

(39209, 25, 25)
(39209,)


In [17]:
train_labels


array([ 0,  0,  0, ..., 42, 42, 42])

In [18]:
import numpy as np
###flat train and test dataset-----------
train=[]
test=[]
for i in train_features:
    train.append(i.flatten())
for i in test_features:
    test.append(i.flatten())
train=np.array(train)
test=np.array(test)

In [19]:
train_features=train
test_features=test

In [20]:
print(train_features.shape)
print(test_features.shape)
print(train_labels.shape)
print(test_labels.shape)

(39209, 625)
(12630, 625)
(39209,)
(12630,)


In [2]:
from six.moves import cPickle
###  http://deeplearning.net/software/theano/tutorial/loading_and_saving.html

In [22]:
### store tain_features in 
f = open('train_feature', 'wb')
cPickle.dump(train_features, f, protocol=cPickle.HIGHEST_PROTOCOL)
f.close()

In [23]:
### store tain_labels in 
f = open('train_label', 'wb')
cPickle.dump(train_labels, f, protocol=cPickle.HIGHEST_PROTOCOL)
f.close()

In [24]:
### store test_features in 
f = open('test_feature', 'wb')
cPickle.dump(test_features, f, protocol=cPickle.HIGHEST_PROTOCOL)
f.close()

In [25]:
### store tain_labels in 
f = open('test_label', 'wb')
cPickle.dump(test_labels, f, protocol=cPickle.HIGHEST_PROTOCOL)
f.close()

In [3]:
f = open('train_feature', 'rb')
train_features= cPickle.load(f)
f.close()

In [4]:
f = open('test_feature', 'rb')
test_features= cPickle.load(f)
f.close()

In [5]:
f = open('train_label', 'rb')
train_labels= cPickle.load(f)
f.close()

In [6]:
f = open('test_label', 'rb')
test_labels= cPickle.load(f)
f.close()


In [7]:
from numpy import array
from numpy import argmax
import scipy
from matplotlib import pyplot as plt
from scipy.misc import imread
import numpy as np
from scipy.misc import imresize
import os
from keras.utils.np_utils import to_categorical
train_labels = array(train_labels)
test_labels=array(test_labels)
encoded_train_labels = to_categorical(train_labels)
encoded_test_labels = to_categorical(test_labels)

c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [30]:
print(encoded_train_labels)
print(encoded_test_labels)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [31]:
encoded_test_labels.shape

(12630, 43)

In [32]:
encoded_train_labels.shape

(39209, 43)

In [8]:
### combine train and test features
total_features = np.concatenate((train_features,test_features) , axis=0)
print(total_features.shape)

(51839, 625)


In [9]:
### combine train and test labels
total_features = np.concatenate((train_features,test_features) , axis=0)
total_labels = np.concatenate((encoded_train_labels,encoded_test_labels) , axis=0)
print(total_labels.shape)

(51839, 43)


In [10]:
from sklearn.cross_validation import train_test_split
images_train , images_test , labels_train , labels_test = train_test_split(total_features,total_labels,test_size = 0.2, random_state=10)

c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.optimizers import Adagrad
from keras.layers.normalization import BatchNormalization


In [12]:
images_train = images_train.reshape(images_train.shape[0], 25, 25, 1)
images_test = images_test.reshape(images_test.shape[0], 25, 25 ,1)

In [13]:
images_train = images_train.astype('float32')
images_test = images_test.astype('float32')
labels_train = labels_train.astype('float32')
labels_test = labels_test.astype('float32')


In [39]:
model = Sequential()
 
model.add(Convolution2D(32, 3, 3, init = 'uniform', input_shape=(25,25,1)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Convolution2D(16, 3, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
 

model.add(Flatten())

model.add(Dense(500, init='uniform'))
model.add(BatchNormalization())
model.add(Activation('relu'))

model.add(Dense(250, init='uniform'))
model.add(BatchNormalization())
model.add(Activation('relu'))

model.add(Dense(100, init='uniform'))
model.add(BatchNormalization())
model.add(Activation('relu'))


model.add(Dense(43, activation='sigmoid'))


learning_rate=0.001
# Compile model
momentum = 0.8
epochs = 50
#keras.optimizers
decay_rate = learning_rate / epochs
sgd = Adagrad(lr=learning_rate,  decay=decay_rate)
model.compile(loss='mean_squared_error', optimizer=sgd, metrics=['accuracy'])
 



c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(25, 25, 1..., kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), activation="relu")`
  
c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(500, kernel_initializer="uniform")`
  del sys.path[0]
c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:17: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(250, kernel_initializer="uniform")`
c:\users\akash\appdata\local\programs\python\python36\lib\site-packag

In [40]:
model.fit(images_train,labels_train, nb_epoch=150, verbose=2 , validation_split=0.1)

c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\keras\models.py:981: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 37323 samples, validate on 4148 samples
Epoch 1/150
 - 180s - loss: 0.0589 - acc: 0.1776 - val_loss: 0.0293 - val_acc: 0.3079
Epoch 2/150
 - 174s - loss: 0.0248 - acc: 0.3850 - val_loss: 0.0204 - val_acc: 0.5019
Epoch 3/150
 - 197s - loss: 0.0192 - acc: 0.5377 - val_loss: 0.0159 - val_acc: 0.6328
Epoch 4/150
 - 157s - loss: 0.0159 - acc: 0.6355 - val_loss: 0.0131 - val_acc: 0.7167
Epoch 5/150
 - 151s - loss: 0.0135 - acc: 0.7073 - val_loss: 0.0109 - val_acc: 0.7883
Epoch 6/150
 - 151s - loss: 0.0117 - acc: 0.7657 - val_loss: 0.0092 - val_acc: 0.8363
Epoch 7/150
 - 150s - loss: 0.0103 - acc: 0.8063 - val_loss: 0.0078 - val_acc: 0.8655
Epoch 8/150
 - 150s - loss: 0.0091 - acc: 0.8336 - val_loss: 0.0069 - val_acc: 0.8872
Epoch 9/150
 - 170s - loss: 0.0082 - acc: 0.8541 - val_loss: 0.0061 - val_acc: 0.9007
Epoch 10/150
 - 204s - loss: 0.0075 - acc: 0.8724 - val_loss: 0.0055 - val_acc: 0.9139
Epoch 11/150
 - 197s - loss: 0.0069 - acc: 0.8848 - val_loss: 0.0050 - val_acc: 0.9221
Epo

Epoch 93/150
 - 178s - loss: 0.0016 - acc: 0.9831 - val_loss: 9.9749e-04 - val_acc: 0.9863
Epoch 94/150
 - 183s - loss: 0.0016 - acc: 0.9831 - val_loss: 9.9208e-04 - val_acc: 0.9863
Epoch 95/150
 - 183s - loss: 0.0016 - acc: 0.9828 - val_loss: 9.8555e-04 - val_acc: 0.9858
Epoch 96/150
 - 177s - loss: 0.0016 - acc: 0.9834 - val_loss: 9.8257e-04 - val_acc: 0.9863
Epoch 97/150
 - 178s - loss: 0.0016 - acc: 0.9832 - val_loss: 9.8136e-04 - val_acc: 0.9860
Epoch 98/150
 - 174s - loss: 0.0015 - acc: 0.9840 - val_loss: 9.7986e-04 - val_acc: 0.9863
Epoch 99/150
 - 196s - loss: 0.0015 - acc: 0.9832 - val_loss: 9.7597e-04 - val_acc: 0.9865
Epoch 100/150
 - 181s - loss: 0.0016 - acc: 0.9825 - val_loss: 9.6508e-04 - val_acc: 0.9860
Epoch 101/150
 - 176s - loss: 0.0015 - acc: 0.9837 - val_loss: 9.6652e-04 - val_acc: 0.9867
Epoch 102/150
 - 189s - loss: 0.0015 - acc: 0.9835 - val_loss: 9.6134e-04 - val_acc: 0.9865
Epoch 103/150
 - 181s - loss: 0.0015 - acc: 0.9842 - val_loss: 9.4920e-04 - val_acc: 0.

In [41]:
scores = model.evaluate(images_test, labels_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100)) 

10368/10368 [==============================] - 18s 2ms/step

acc: 99.05%


In [42]:
# serialize model to JSON
model_json = model.to_json()
with open("final_model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("final_model.h5")
print("Saved model to disk")

Saved model to disk


In [16]:
predict=model.predict(images_test)

NameError: name 'model' is not defined

In [1]:
print(predict[10])
print(labels_test[10])

NameError: name 'predict' is not defined

In [45]:
from sklearn.metrics import roc_curve, auc
%matplotlib inline

In [46]:
def generate_results(y_test, y_score):
    fpr, tpr, _ = roc_curve(y_test, y_score)
    roc_auc = auc(fpr, tpr)
    plt.figure()
    plt.plot(fpr, tpr, 'r',label='ROC curve (area = %0.2f)' % roc_auc)
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlim([0.0, 1.05])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic curve')
    plt.show()

In [14]:
from keras.models import model_from_json
# load json and create model
json_file = open('final_model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("final_model.h5")
print("Loaded model from disk")

#compiling model
learning_rate=0.001
# Compile model
momentum = 0.8
epochs = 50
#keras.optimizers
decay_rate = learning_rate / epochs
sgd = Adagrad(lr=learning_rate,  decay=decay_rate)
loaded_model.compile(loss='mean_squared_error', optimizer=sgd, metrics=['accuracy'])
print("Model compiled")

Loaded model from disk
Model compiled


In [15]:
scores = loaded_model.evaluate(images_test, labels_test)
print("\n%s: %.2f%%" % (loaded_model.metrics_names[1], scores[1]*100))

10368/10368 [==============================] - 22s 2ms/step

acc: 99.05%
